name: Check pxt.json

on: push

jobs:
  check-cfg:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install PXT and set target
        run: |
          npm install -g pxt
          pxt target microbit

      - name: Reset working directory
        run: |
          git checkout -- .
          git clean -fd

      - name: Fix files listed in config if necessary
        run: pxt checkpkgcfg

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Removing missing files from pxt.json"
          commit-message: "Removing missing files from pxt.json"
          delete-branch: true
