name: MakeCode

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install PXT and set target
        run: |
          npm install -g pxt
          pxt target microbit

      - name: Install dependencies
        run: pxt install

      - name: Build project
        run: pxt build --cloud
        env:
          CI: true
